#syntax=docker/dockerfile:1.2
FROM node:20-alpine
WORKDIR /srv/app
COPY ./package.json ./
COPY ./package-lock.json ./
COPY config ./config
COPY public ./public
COPY init ./init
COPY src ./src
RUN npm run init || true
EXPOSE 1337
CMD ["npm", "run", "develop"]
