name: 'coverage'
on:
  push:
    branches:
      - becevka/jest-tests
    workflow_dispatch:
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: '18.x'
            - run: npm install
            - run: npm run test
              env:
                CI: false
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                coverage-file: ./coverage/coverage-final.json
                base-coverage-file: ./coverage/coverage-final.json