name: Publish Types

on:

  push:
    branches:
      - main

    paths-ignore:

      - 'staging/**'
      - 'production/**'
     
      - "**/*.md"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url : 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

# CHANGE THE PIPELINE INTO 2 SEPARATE WORKFLOW
      - name: Update version
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')
          echo "Updating package.json version to $VERSION"
          jq ".version = \"$VERSION\"" types/package.json > temp.json && mv temp.json types/package.json

      - name: Publish types
        run: cd types && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
