name: test
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies in src/plugins/googledrive
        run: |
          cd src/plugins/googledrive
          npm ci

      - name: Install dependencies
        run: npm ci
        # TODO: Add step for linting

      - name: Run Playwright tests
        run: npm run test:postgres
        env:
          CI: true
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/cobertura-coverage.xml'
          badge: true
          format: 'markdown'
          hide_complexity: true
          thresholds: '65 85'
          output: 'both'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          # Don't push image
          push: false
          # Get cache from latest build on main branch
          cache-from: type=gha
          # Don't set cache-to which will export the cache
